### ISSUE TITLE
Problem with the date header format

### ISSUE THREAD

**Issue by s3bi** [i8beef/I8Beef.Neato#1]
To run the code from other countries, the date header format has to be changed by setting the culture info to en-US. This would be very helpfull.
File: NucleoClient.cs
Line: 186
![image](https://user-images.githubusercontent.com/7644815/77846013-4fcad900-71b3-11ea-9eec-0f1777026304.png)

**Comment by i8beef** [comment]
Did you already make this change in a local copy and test it? If so, Ill go ahead and make the change and get a new version out quick.

**Comment by s3bi** [comment]
Yes. I tested it.
Without the change the day part is in the local language. E.g. on sunday it is "So" instead of "Sun".
The main point is to make sure that the day part is in english. I guess you can use "en-EN" as well.

**Comment by s3bi** [comment]
Actually i'm not able to create a pull request otherwise i would send my changes.

**Comment by i8beef** [comment]
1,0.0.16 Should incorporate this.
